// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpnewBsZMpCo_2w5VixY-27XeuDtI5vNs',
    appId: '1:452087933226:web:071e0577116beb8d6ed653',
    messagingSenderId: '452087933226',
    projectId: 'flutter-test-9a97a',
    authDomain: 'flutter-test-9a97a.firebaseapp.com',
    storageBucket: 'flutter-test-9a97a.appspot.com',
    measurementId: 'G-GRTVNCGBH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCyaoVf7JxShOkbM8O9Pgdq2VTDm019D3o',
    appId: '1:452087933226:android:500439f3f8bdd5b36ed653',
    messagingSenderId: '452087933226',
    projectId: 'flutter-test-9a97a',
    storageBucket: 'flutter-test-9a97a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjcUPZbl_YERMbXlWIEdIYkAlHfzm82os',
    appId: '1:452087933226:ios:82f5bf954448ec9d6ed653',
    messagingSenderId: '452087933226',
    projectId: 'flutter-test-9a97a',
    storageBucket: 'flutter-test-9a97a.appspot.com',
    iosClientId: '452087933226-gslrss6ja31hdcq856k2t20no1fhen07.apps.googleusercontent.com',
    iosBundleId: 'com.example.adamurFlutterEngineerTestHabbaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjcUPZbl_YERMbXlWIEdIYkAlHfzm82os',
    appId: '1:452087933226:ios:82f5bf954448ec9d6ed653',
    messagingSenderId: '452087933226',
    projectId: 'flutter-test-9a97a',
    storageBucket: 'flutter-test-9a97a.appspot.com',
    iosClientId: '452087933226-gslrss6ja31hdcq856k2t20no1fhen07.apps.googleusercontent.com',
    iosBundleId: 'com.example.adamurFlutterEngineerTestHabbaApp',
  );
}
